# ---------------------------------------------------------
# Blog infos
# ---------------------------------------------------------
description: Questo è il sito del matrimonio francescano
metadata: matrimonio, cristiano, amore
url: http://matrimoniofrancescano.it

# ---------------------------------------------------------
# Blog basic design
# ---------------------------------------------------------
logo:    images/favicon/logo-128.jpg
favicon: images/favicon/logo-128.jpg
header:  images/header/header.png

# ---------------------------------------------------------
# Accounts
# ---------------------------------------------------------
# google_analytics: 87364

# ---------------------------------------------------------
# Jekyll stuff
# ---------------------------------------------------------
permalink: /:categories/:title
markdown: kramdown
timezone: Europe/Rome
future: false
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
