# ---------------------------------------------------------
# Blog infos
# ---------------------------------------------------------
description: Il sito del matrimonio francescano
metadata: matrimonio, cristiano, amore
url: http://matrimoniofrancescano.it

# ---------------------------------------------------------
# Blog basic design
# ---------------------------------------------------------
logo:    /images/favicon/logo-128.jpg
favicon: /images/favicon/logo-128.jpg
header:  /images/header/header.png
fb_img:  /images/posts/il-matrimonio-francescano.jpg

# ---------------------------------------------------------
# Authors
# ---------------------------------------------------------
authors:

    - name: ruvido
      display: Alessandra e Francesco

    - name: alescanca
      display: Alessandra e Francesco

    - name: luca
      display: Chiara e Luca

    - name: chiara
      display: Chiara e Luca

    - name: guest
      display: una coppia di sposi

# ---------------------------------------------------------
# Menus
# ---------------------------------------------------------
menu:

  - title: "Articoli"
    href: "/articoli"

  - title: "Testimonianze"
    href: "/testimonianze"

  - title: "Chi siamo"
    href: "/chi-siamo"

  - title: "Consigli pratici"
    href: "/consigli-pratici"
# ---------------------------------------------------------
footer_menu:

  - title: "Archivio"
    href: "/articoli"

  - title: "Scrivici"
    href: "mailto:info@matrimoniofrancescano.it"

  - title: "Facebook"
    href: "https://www.facebook.com/MatrimonioFrancescano"

# ---------------------------------------------------------
# Accounts
# ---------------------------------------------------------
google_analytics: UA-69446168-1

# ---------------------------------------------------------
# Jekyll stuff
# ---------------------------------------------------------
images: /images/posts
previews: /previews
permalink: /:categories/:title/
# permalink: pretty
markdown: kramdown
timezone: Europe/Rome
future: false
sass:
  style: compressed
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
      author: "guest"
