# ---------------------------------------------------------
# Blog infos
# ---------------------------------------------------------
description: Questo è il sito del matrimonio francescano
metadata: matrimonio, cristiano, amore
url: http://matrimoniofrancescano.it

# ---------------------------------------------------------
# Blog basic design
# ---------------------------------------------------------
logo:    /images/favicon/logo-128.jpg
favicon: /images/favicon/logo-128.jpg
header:  /images/header/header.png
fb_img:  /images/posts/il-matrimonio-francescano.jpg


# ---------------------------------------------------------
# Menus
# ---------------------------------------------------------
menu:

  - title: "Articoli"
    href: "/articoli"

  - title: "Testimonianze"
    href: "/testimonianze"

  - title: "Chi siamo"
    href: "/chi-siamo"

  - title: "Consigli pratici"
    href: "/consigli-pratici"
# ---------------------------------------------------------
footer_menu:

  - title: "Archivio"
    href: "/articoli"

  - title: "Scrivici"
    href: "mailto:info@matrimoniofrancescano.it"

  - title: "Facebook"
    href: "https://www.facebook.com/MatrimonioFrancescano"

# ---------------------------------------------------------
# Accounts
# ---------------------------------------------------------
# google_analytics: 87364

# ---------------------------------------------------------
# Jekyll stuff
# ---------------------------------------------------------
images: /images/posts
permalink: /:categories/:title
markdown: kramdown
timezone: Europe/Rome
future: false
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
