#!/usr/bin/env ruby

# require 'the_jekyll_editor'
require '/Users/ruvido/Dropbox/development/the_jekyll_editor/lib/the_jekyll_editor'


# ===================
# CONFIGURATION
# ===================

iblog="/Users/ruvido/Dropbox/web/matrimoniofrancescano.it"
idump="#{iblog}/__writing"

myblog=Blogdata.new( idump, iblog )


[ myblog.dump_previews, myblog.dump_drafts ].each do |cdir|

  Dir["#{cdir}/{[!_]**/*,*}.md"].each do |ii|



    draft=Draft.new(ii,myblog)
    status = draft.status

    case status
    when "publish"
      puts '--------------------------------'
      puts draft.basename, draft.filename, draft.image, status
      draft.to_posts
      puts "file published!"
    when "preview"
      puts '--------------------------------'
      puts draft.basename, draft.title, draft.image, status
      draft.missing
      draft.to_previews
      # puts "file sent to previews, want the address?"
    # when "draft"
      # puts "keep working on that!"
    end    

  end
end

  puts '--------------------------------'

if 1

  # date = DateTime.now
  date = Time.now
  today=date.strftime("%d-%m-%Y")
  # Dir.chdir iblog
  f = File.open("#{iblog}/today", "w+")
  f.puts today
  f.close

end

# sleep 1
# myblog.push

Dir.chdir iblog
`git add --all .`
`git commit -a -m 'commit'`
`git push`
